### ISSUE TITLE
Bug in Country Field 

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#52]
It appears that when you select a country in the last form of the claim form, the country doesn't appear in bold white as the rest does. 
please fix this. 

![capture d ecran 2015-02-12 a 23 01 24](https://cloud.githubusercontent.com/assets/10349847/6177971/1e48f81a-b30b-11e4-999c-621f98cae125.png)

**Comment by krasizlatev** [comment]
Fixed.

**Comment by drosne** [comment]
Thx

**Comment by drosne** [comment]
Actually .. still have a problem .. check this out : 
![capture d ecran 2015-02-23 a 11 00 39](https://cloud.githubusercontent.com/assets/10349847/6325941/d59cc6a6-bb4c-11e4-9862-ce8bcd5de62c.png)
The color is ok but the country is supposed to be in bold.
