### ISSUE TITLE
Sliders Dots

### ISSUE THREAD

**Issue by drosne** [drosne/RMT#6]
in the mobile version, it seems that the sliders dots are not always the same number available on one single row. 
Is it possible to have the maximum dots on a single row and have the same number of dots on a row for each sliders in the home page and everywhere actually (if there are some sliders anywhere else). 
![photo](https://cloud.githubusercontent.com/assets/10349847/5579798/8c10abf6-9040-11e4-8fcd-ef2b7ed9779b.PNG)

**Comment by nppetrov** [comment]
We will increase the maximum width of the row. Will send the fixed scss file via e-mail.

**Comment by drosne** [comment]
that's strange.. I still get the same design...
i tried to clear my cache and nothing has changed... can you please check on your mobile if you can and let me know if it's supposed to be changed...

**Comment by nppetrov** [comment]
I noticed one of the sliders still have issue with the first row width.. will make sure we fix this today and will send you updated scss.

**Comment by drosne** [comment]
on my side on my iPhone they all still have some dots on 2 lines...

**Comment by nppetrov** [comment]
Fixed (latest files sent via e-mail).

**Comment by drosne** [comment]
not fixed on my phone ... 
same problem in the home page with the sliders dots which are still on two lines on my iphone 5S

**Comment by nppetrov** [comment]
Fixes were sent via e-mail, I guess they are still not uploaded to beta.

**Comment by drosne** [comment]
fixed yes .. thanks
